create table base_resource_authority
(
	id INTEGER not null
		constraint INDEX33557407
			primary key,
	authority_id VARCHAR(255),
	authority_type VARCHAR(255),
	resource_id VARCHAR(255),
	resource_type VARCHAR(255),
	parent_id VARCHAR(255),
	path VARCHAR(2000),
	description VARCHAR(255),
	crt_time TIMESTAMP(26,6),
	crt_user VARCHAR(255),
	crt_name VARCHAR(255),
	crt_host VARCHAR(255),
	attr1 VARCHAR(255),
	attr2 VARCHAR(255),
	attr3 VARCHAR(255),
	attr4 VARCHAR(255),
	attr5 VARCHAR(255),
	attr6 VARCHAR(255),
	attr7 VARCHAR(255),
	attr8 VARCHAR(255)
);

INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2165, '1', 'group', '1', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2166, '1', 'group', '5', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2167, '1', 'group', '4', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2168, '1', 'group', '5', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2169, '1', 'group', '6', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2170, '1', 'group', '7', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2171, '1', 'group', '8', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2172, '1', 'group', '9', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2173, '1', 'group', '10', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2174, '1', 'group', '19', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2175, '1', 'group', '20', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2176, '1', 'group', '6', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2177, '1', 'group', '11', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2178, '1', 'group', '12', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2179, '1', 'group', '13', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2180, '1', 'group', '14', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2181, '1', 'group', '15', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2182, '1', 'group', '16', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2183, '1', 'group', '17', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2184, '1', 'group', '21', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2185, '1', 'group', '26', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2186, '1', 'group', '7', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2187, '1', 'group', '22', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2188, '1', 'group', '23', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2189, '1', 'group', '24', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2190, '1', 'group', '25', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2191, '1', 'group', '8', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2192, '1', 'group', '27', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2193, '1', 'group', '44', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2316, '9', 'group', '37', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2317, '9', 'group', '1', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2318, '9', 'group', '5', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2319, '9', 'group', '4', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2320, '9', 'group', '5', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2321, '9', 'group', '6', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2322, '9', 'group', '7', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2323, '9', 'group', '8', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2324, '9', 'group', '9', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2325, '9', 'group', '10', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2326, '9', 'group', '19', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2327, '9', 'group', '20', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2328, '9', 'group', '6', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2329, '9', 'group', '12', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2330, '9', 'group', '14', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2331, '9', 'group', '15', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2332, '9', 'group', '16', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2333, '9', 'group', '17', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2334, '9', 'group', '7', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2335, '9', 'group', '22', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2336, '9', 'group', '23', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2337, '9', 'group', '24', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2338, '9', 'group', '25', 'button', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2339, '9', 'group', '8', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2340, '9', 'group', '27', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2341, '9', 'group', '44', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2342, '9', 'group', '45', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2343, '9', 'group', '46', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2344, '9', 'group', '47', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2345, '9', 'group', '48', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO IPSM_DBA.base_resource_authority (id, authority_id, authority_type, resource_id, resource_type, parent_id, path, description, crt_time, crt_user, crt_name, crt_host, attr1, attr2, attr3, attr4, attr5, attr6, attr7, attr8) VALUES (2346, '9', 'group', '49', 'menu', '-1', null, null, null, null, null, null, null, null, null, null, null, null, null, null);